import { BadRequestException } from '@nestjs/common';
import { createHash, randomBytes } from 'crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Where feedback screenshots live: **the filesystem, not the database.**
 *
 * ## The constraint that decides this
 *
 * The backend runs sql.js — SQLite compiled to wasm — which holds the entire
 * database in memory and rewrites the whole file on every flush. Anything
 * stored in a column is therefore re-serialised on every unrelated write for as
 * long as it exists. `users.profileImage` is already base64 in a column and is
 * the reason posts refuse photos outright (`MEMORY.md`, 2026-08-07).
 *
 * Feedback genuinely needs images, so the bytes go to disk and the row keeps
 * only a filename. This is the first thing in the project to store a file, so
 * the rules below are the pattern for anything that follows.
 *
 * ## Operational notes
 *
 * - The directory sits **outside the git checkout's tracked content** but inside
 *   the app directory: `backend/uploads/feedback/`. It is gitignored, so
 *   `deploy.sh`'s `git reset --hard` cannot delete it — the same property that
 *   keeps `.env` and the database alive across deploys.
 * - It is **not** covered by `deploy-dev.sh`'s database snapshot. Losing an
 *   attachment loses a screenshot, not a workout; that is an acceptable
 *   asymmetry, and stated here so nobody assumes otherwise.
 * - Nothing is served statically. Bytes come back through an authenticated
 *   endpoint (`GET /feedback/:id/image/:filename`) so an attachment cannot be
 *   enumerated by guessing URLs.
 *
 * ## ponytail
 *
 * ponytail: local disk, single host. Fine while one Pi serves the app. If
 * RepRush ever runs on more than one machine, or attachments need a CDN, move
 * this to object storage — every caller goes through `saveDataUrl` / `readFile`
 * / `deleteFiles`, so the swap is this file only.
 */

/** Image types accepted. JPEG and PNG cover every phone screenshot path. */
const ALLOWED = new Map<string, string>([
  ['image/jpeg', 'jpg'],
  ['image/png', 'png'],
  ['image/webp', 'webp'],
]);

/**
 * Per-image ceiling **after** the client has downscaled.
 *
 * The client compresses to ~1600px JPEG before upload, which lands around
 * 200–400 KB. 3 MB is therefore generous, and exists to stop an unmodified
 * client (or a hand-rolled request) writing a 20 MB file to the Pi's SD card.
 */
const MAX_BYTES = 3 * 1024 * 1024;

/** Attachments per report. Enough to show a flow, not enough to fill a disk. */
export const MAX_IMAGES = 6;

/** Resolved lazily so tests and scripts can import this without side effects. */
function dir(): string {
  // `__dirname` is `dist/feedback` at runtime, so two levels up is `backend/`.
  const path = join(__dirname, '..', '..', 'uploads', 'feedback');
  if (!existsSync(path)) mkdirSync(path, { recursive: true });
  return path;
}

/**
 * A filename that cannot escape the upload directory.
 *
 * Every read path runs through this. The stored name is generated by us, but
 * the *requested* name arrives in a URL, and `../../.env` is a valid string.
 * Rejecting anything outside `[A-Za-z0-9_.-]` is simpler to verify than
 * normalising a path and comparing prefixes, and it cannot be defeated by
 * encoding tricks because the check happens after the framework has decoded.
 */
function assertSafeName(name: string): string {
  if (!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,99}$/.test(name) || name.includes('..')) {
    throw new BadRequestException('Bad attachment name');
  }
  return name;
}

/**
 * Decode one `data:` URL and write it to disk.
 *
 * @param dataUrl  `data:image/jpeg;base64,…` as produced by the client's canvas
 *                 compressor. Anything else is rejected.
 * @param ownerId  Only used to make the filename readable while debugging; it
 *                 is **not** an access-control mechanism — see `readFile`.
 * @returns        The stored filename, to be kept in `feedback.images`.
 *
 * @throws BadRequestException on an unsupported type or an oversized payload.
 *
 * Uploads are accepted as base64 inside the JSON body rather than as multipart,
 * which is why this takes a string. That choice avoids adding multer and its
 * types for one form; the cost is ~33% transfer overhead, which at ≤6 images of
 * ≤400 KB stays far inside nginx's 12 MB `client_max_body_size`.
 */
export function saveDataUrl(dataUrl: string, ownerId: number): string {
  const match = /^data:([^;,]+);base64,(.+)$/s.exec(String(dataUrl ?? ''));
  if (!match) throw new BadRequestException('Attachments must be base64 data URLs');

  const ext = ALLOWED.get(match[1].toLowerCase());
  if (!ext) throw new BadRequestException(`Unsupported image type: ${match[1]}`);

  const buf = Buffer.from(match[2], 'base64');
  if (!buf.length) throw new BadRequestException('Empty attachment');
  if (buf.length > MAX_BYTES) {
    throw new BadRequestException(`Each image must be under ${Math.round(MAX_BYTES / 1024 / 1024)} MB`);
  }

  // Random, not a hash of the content: identical screenshots from two people
  // must not collide onto one file, or deleting either report would break the
  // other. The short content hash is only a debugging aid.
  const name = `fb_${ownerId}_${randomBytes(6).toString('hex')}_${createHash('sha1')
    .update(buf)
    .digest('hex')
    .slice(0, 6)}.${ext}`;

  writeFileSync(join(dir(), name), buf);
  return name;
}

/**
 * Read one attachment back.
 *
 * **This function performs no authorisation.** The caller must have already
 * established that the requester may see the report the file belongs to, and
 * must have checked that `name` is listed on that report — otherwise knowing
 * any filename would be enough to read any file. `FeedbackService.readImage`
 * is the only intended caller and does both.
 *
 * @returns the bytes, or null if the file is gone (a report can outlive its
 *          attachment if the disk was restored from an older backup).
 */
export function readFile(name: string): Buffer | null {
  const safe = assertSafeName(name);
  const path = join(dir(), safe);
  if (!existsSync(path)) return null;
  return readFileSync(path);
}

/** Best-effort cleanup. A missing file is success — the goal is that it is gone. */
export function deleteFiles(names: string[]): void {
  for (const name of names ?? []) {
    try {
      rmSync(join(dir(), assertSafeName(name)), { force: true });
    } catch {
      // Deliberately swallowed: failing to delete a screenshot must never fail
      // the request that deletes the report it belonged to.
    }
  }
}

/** Content type for a stored filename, derived from its extension. */
export function contentTypeFor(name: string): string {
  const ext = name.split('.').pop()?.toLowerCase();
  for (const [mime, e] of ALLOWED) if (e === ext) return mime;
  return 'application/octet-stream';
}

/**
 * Boundary assertions. Run at boot beside every other `__selfcheck` — the path
 * guard in particular is security-relevant, and an assertion is a comment that
 * cannot go stale.
 */
export const __selfcheck = () => {
  const assert = (cond: boolean, msg: string) => {
    if (!cond) throw new Error(`attachment.store: ${msg}`);
  };
  const rejects = (name: string) => {
    try {
      assertSafeName(name);
      return false;
    } catch {
      return true;
    }
  };

  assert(rejects('../../../etc/passwd'), 'traversal is rejected');
  assert(rejects('..'), 'bare dot-dot is rejected');
  assert(rejects('a/b.jpg'), 'a path separator is rejected');
  assert(rejects('a\\b.jpg'), 'a backslash is rejected');
  assert(rejects(''), 'an empty name is rejected');
  assert(rejects('.hidden'), 'a leading dot is rejected');
  assert(!rejects('fb_5_a1b2c3_d4e5f6.jpg'), 'a generated name is accepted');

  assert(contentTypeFor('x.jpg') === 'image/jpeg', 'jpg maps to image/jpeg');
  assert(contentTypeFor('x.exe') === 'application/octet-stream', 'unknown falls back');

  return 'attachments ok';
};
